### ISSUE TITLE
垂直居中实现方式总结

### ISSUE THREAD

**Issue by gou-tian** [gou-tian/gou-tian.github.io#1]
**方法一 利用 line-height 实现垂直居中**
```css
    #example1 {
        height: 100px;
        line-height: 100px;
        background: #161616;
        color: #fff;
        width: 200px;
    }
```
```html
    <div id="example1">单行文字垂直居中</div>
```
这种方法适用于单行文本垂直居中,如果文本内容太长，出现了换行，换行后的内容会溢出。

**方法二 利用 display: table 实现垂直居中**
```css
    #example2 {
        height: 100px;
        background: #161616;
        color: #fff;
        width: 400px;
        overflow: hidden;
        display: table;
    }
    #example2 .inner{
        display: table-cell;
        vertical-align: middle;
        height: 50px;
        background:#999;
    }
```
```html
    <div id="example2">
        <div class="inner">块区域垂直居中</div>
    </div>
```

**方法三 margin 填充**
```css
    #example3 {
        height: 100px;
        background: #161616;
        color: #fff;
        width: 400px;
        overflow: hidden;
    }
    #example3 .inner{
        margin-left: auto;
        margin-right: auto;
        margin-top: calc((100px - 50px)/2);
        height: 50px;
        background:#999;
    }
```
```html
    <div id="example3">
        <div class="inner">块区域垂直居中</div>
    </div>
```
这种方法需要知道内外容器的大小

**方法四 经典 absolute 布局上下文垂直居中**
```css
    #example4 {
        width: 400px;
        height: 100px;
        background: #161616;
        color: #fff;
        position: relative;
    }
    #example4 .inner{
        height: 50px;
        width: 200px;
        position: absolute;
        left: 50%;
        top: 50%;
        margin-top: -25px;
        margin-left: -100px;
        background:#999;
    }
```
```html
    <div id="example4">
        <div class="inner">块区域垂直居中</div>
    </div>
```
这种方法内部容器的宽高，外部容器的宽高可以不定

**方法五 Css3下 absolute 布局上下文垂直居中**
```css
    #example5 {
        width: 400px;
        height: 100px;
        background: #161616;
        color: #fff;
        position: relative;
    }
    #example5 .inner{
        position: absolute;
        left: 50%;
        top: 50%;
        background: #999;
        transform: translateX(-50%) translateY(-50%);
    }
```
```html
    <div id="example5">
        <div class="inner">块区域垂直居中</div>
    </div>
```
这种方法内外容器都可以是不定的

**方法六 利用margin：auto 居中**
```css
    #expample6 {
        width: 400px;
        height: 100px;
        background: #eee;
        position: relative;
    }
    
    #expample6 .inner {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        margin: auto;
        height: 50px;
        width: 70%;
        background: #aaa;
        color:#222;
    }
```
```html
    <div id="expample6">
        <div class="inner">Content here</div>
    </div>
```

**方法七 利用 Flex布局 居中**
```css
    #expample7 {
        width: 400px;
        height: 100px;
        background: #eee;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    
    #expample7 .inner {
        height: 50px;
        width: 70%;
        background: #aaa;
        color:#222;
    }
```
```html
    <div id="expample7">
        <div class="inner">Content here</div>
    </div>
```
